import type { Metadata } from "next";
import {
  Inter,
  Montserrat_Alternates,
  Nunito_Sans,
  Rufina,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

// const inter = Inter({ subsets: ["latin"] });
// const montserratAlternates = Montserrat_Alternates({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-montserrat-alternates",
//   display: "swap",
// });

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito-sans",
  display: "swap",
});

const rufina = Rufina({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-rufina",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} ${rufina.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
